### ISSUE TITLE
Bug - only one listing shown in list

### ISSUE THREAD

**Issue by claratee** [ResilienceWeb/resilience-web#108]
I'm logged in as clarabara@gmail.com.

Expected: all listings in Cambridge city shown on the Cambridge city dashboard 

Actual: only one listing - Cambridge Doughnut - shown 

Oddly, I appear to able to create a listing, but I just can't see em! I added growkids.

**Comment by DinerIsmail** [comment]
@claratee looks like you had only 1 permission for the Cambridge Doughnut listing. You previously could do a lot more as you were set as an admin, but with the platform growing I minimised the checks for the 'admin' role and replaced that with the ownership functionality (which I will show more about soon).
I think the fact you were allowed to create listings was because you were still an admin.

Hope it should all look ok now?
